package academy.devdojo.maratonajava.javacore.ZZG_Concurrent.test;

import academy.devdojo.maratonajava.javacore.ZZG_Concurrent.domain.Quote;
import academy.devdojo.maratonajava.javacore.ZZG_Concurrent.service.StoreServiceWithDiscount;

import java.util.List;
import java.util.concurrent.CompletableFuture;

public class CompletableFutureTest04 {
    static void main() {
        StoreServiceWithDiscount service = new StoreServiceWithDiscount();
        searchPricesWithDiscountAsync(service);
    }

    private static void searchPricesWithDiscount(StoreServiceWithDiscount service) {
        long start = System.currentTimeMillis();

        List<String> stores = List.of("Store1", "Store2", "Store3", "Store4");
        //stores.forEach(s -> System.out.println(service.getPriceSync(s)));
        stores.stream()
                .map(service::getPriceSync) // store:price:code
                .map(Quote::newQuote)// generate a new Quote
                .map(service::applyDiscount) // apply the discount
                .forEach(System.out::println);

        long end = System.currentTimeMillis();
        System.out.printf("Time passed to searchPricesSync %dms%n", (end - start));
    }

    private static void searchPricesWithDiscountAsync(StoreServiceWithDiscount service) {
        long start = System.currentTimeMillis();

        List<String> stores = List.of("Store1", "Store2", "Store3", "Store4");

        List<CompletableFuture<String>> completableFutures = stores.stream()
                // Getting the price async storeName:price:discountCode
                .map(store -> CompletableFuture.supplyAsync(() -> service.getPriceSync(store)))
                // Instantiating a new Quote from the string generated by getPriceSync (first map)
                .map(cf -> cf.thenApply(Quote::newQuote))
                // Composing the first completable future
                .map(cf -> cf.thenCompose(quote -> CompletableFuture.supplyAsync(() -> service.applyDiscount(quote))))
                .toList();

        completableFutures.stream()
                .map(CompletableFuture::join)
                .forEach(System.out::println);

        long end = System.currentTimeMillis();
        System.out.printf("Time passed to searchPricesSync %dms%n", (end - start));
    }
}
